version: '3.7'

services:

  serve_table_transformer_models:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    image: serve_table_transformer_models
    # command: gunicorn --bind 0.0.0.0:8080 --access-logfile - --error-logfile - manage:app
    container_name: serve_table_transformer_models
    ports:
      - 9000:5000
      - 9001:5001
      - 9002:5002
    volumes:
      - ./model_store:/home/model-server/model_store