# Builder image
FROM pytorch/torchserve:latest-gpu

ADD requirements.txt .
RUN pip install -r requirements.txt
COPY model_store model_store
RUN echo "Archive created!"
ADD scripts/start-torchserve.sh start-torchserve.sh
COPY config.properties config.properties
CMD ["sh ./start-torchserve.sh"]
